### ISSUE TITLE
Failed to build app because of some TS1005 errors

### ISSUE THREAD

**Issue by tatiana-lonestone** [sindresorhus/got#2164]
#### Describe the bug

 - Node.js version:  16.14.2 and 17.0.0 and 18.0.0
 - OS & version: Mac Monterey 12.6
 - Project working with nestjs

`yarn build` failed when I use ^12.4.0 version of got (so on last version too), but it build perfectly on 12.3.1 and before.

`yarn build` call `nest build`

#### Actual behavior

I have this build error : 

```bash
yarn run v1.22.19
warning ../package.json: No license field
$ rimraf dist
$ nest build
node_modules/got/dist/source/core/index.d.ts:15:24 - error TS1005: ',' expected.

15 import Options, { type NativeRequestOptions } from './options.js';
                          ~~~~~~~~~~~~~~~~~~~~
node_modules/got/dist/source/core/index.d.ts:16:15 - error TS1005: ',' expected.

16 import { type PlainResponse, type Response } from './response.js';
                 ~~~~~~~~~~~~~
node_modules/got/dist/source/core/index.d.ts:16:35 - error TS1005: ',' expected.

16 import { type PlainResponse, type Response } from './response.js';
                                     ~~~~~~~~
node_modules/got/dist/source/core/options.d.ts:21:29 - error TS1005: ',' expected.

21 import http2wrapper, { type ClientHttp2Session } from 'http2-wrapper';
                               ~~~~~~~~~~~~~~~~~~

Found 4 error(s).

error Command failed with exit code 1.
```

#### Expected behavior

I would like yarn build work with last version of got

#### Checklist

- [X ] I have read the documentation.
- [ X] I have tried my code with the latest version of Node.js and Got.

Sorry for the english, this is not my first language.

**Comment by sindresorhus** [comment]
I think you need to upgrade your TypeScript version.

**Comment by Sa7cez** [comment]
Have same errors with last version of TypeScript :(
