### PR TITLE
Update some import { type } statements to work with typescript v4.4 and below

### PR DESCRIPTION
**Pull request by hdoan741**
I'm working on a project that's using typescript v4.2. When adding `got` to the project, it threw some typescript errors:

```
../node_modules/got/dist/source/core/index.d.ts(12,15): error TS1005: ',' expected.
../node_modules/got/dist/source/core/index.d.ts(12,35): error TS1005: ',' expected.
../node_modules/got/dist/source/core/options.d.ts(21,29): error TS1005: ',' expected.
```

After some investigation, I found it's because `import { type }` syntax is not supported until typescript v4.5. This change will allow `got` to work with those projects without any patching. 

#### Checklist

- [X] I have read the documentation.
- [X] I have included a pull request description of my changes.
- [ ] I have included some tests.
- [ ] If it's a new feature, I have included documentation updates in both the README and the types.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the PR, but we're not interested in changing this.

**Comment by hdoan741** [comment]
Ok. Make sense, since more people may write code with the newer version of typescript and introduce more of this import style.

**Comment by hdoan741** [comment]
I'll fix mine with a patch for now
