### ISSUE TITLE
Import with typescript  (TS1479)

### ISSUE THREAD

**Issue by alexey-sh** [sindresorhus/got#2206]
#### Describe the bug

Unable to import.

 - Node.js version: v16.15.0
 - OS & version: Mac OS X 12.6
 - Typescript 4.9.4
 - got 12.5.3

#### Actual behavior
Getting error with `npx tsc`
```
 error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("got")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/alexeysh/dev/trash/got-ts/package.json'.
```

#### Expected behavior
no errors, **like on got v11.8.6**
#### Code to reproduce

```ts
// src/index.ts
import got from "got";
```

package.json
```json
{
  "name": "got-ts",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "npx tsc",
    "run": "node --enable-source-maps dist/index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "got": "^12.5.3"
  },
  "devDependencies": {
    "typescript": "^4.9.4"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": [
      "ES2022"
    ],
    "module": "node16",
    "target": "ES2022",
    "moduleResolution": "node16",
    "outDir": "dist",
    "skipLibCheck": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

I tried different target, module, lib but no luck.
The code below works with got v11.8.6.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
The error says it all. You need the `type` field in package.json

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by winstxnhdw** [comment]
You can just set `moduleResolution` to `Bundler` now in TypeScript 5.0

```json
"moduleResolution": "Bundler"
```

Extension types are ugly.
