### ISSUE TITLE
Error TS since update to 14.4.1 : responseType does not exists on type "OptionsOfUnknownResponseBody"

### ISSUE THREAD

**Issue by throrin19** [sindresorhus/got#2357]
#### Describe the bug

 - Node.js version: 20.14.0
 - OS & version: macOs 13.6.7

#### Actual behavior

After update to got 14.4.1 I have several errors in got usage when I pass the property `responseType`. This is an error TS2353 said responseType does not exists on type "OptionsOfUnknownResponseBody" : 

![image](https://github.com/sindresorhus/got/assets/1394778/061130cd-f1c6-4d4e-ba04-7a7e8819ebb5)

After research, the problems is due to modifications introduced by https://github.com/sindresorhus/got/pull/2353. Normally, hotfix version does not introduce breaking changes. Here, it's a breaking change in types declarations.

#### Expected behavior

All works fine, same as 14.4.0

#### Code to reproduce

```js
await got('-/reload', {
        method: 'POST',
        prefixUrl: promServer,
        responseType: 'json',
        retry: {
            limit: 0,
        },
    });
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
// @spence-s

**Comment by spence-s** [comment]
I tried reproducing but it works fine for me and correctly resolves to the OptionsOfJSONResponseBody: 

![Screenshot 2024-06-10 at 9 38 56 AM](https://github.com/sindresorhus/got/assets/16724951/f1b89594-8e7f-4ff0-ba31-c4a86331383f)

After you updated the package did you run `tsc` to prove the error exists or are you only noticing it in your editor? If it's only in editor, then try restarting the editor.

What version of typescript are you using? It's possible that an older version may not resolve correctly.

**Comment by throrin19** [comment]
@spence-s I'm in typescript 5.4.5 but it's my bad. I create a proxy function to capture and format errors with more readable logic for us (retrieve body and simplify error) : 

```
/**
 * Wrapper to got library
 *
 * @param uri - URI to request
 * @param options - Got options
 * @returns Request's response
 */
export const got = async (uri: string | URL, options?: OptionsOfUnknownResponseBody) => {
    try {
        return await originGot(uri, options);
    } catch (err) {
        throw new GotError(err as RequestError);
    }
};
```

But i made a mistake in it. How to retrieve a type with all available options to replace `OptionsOfUnknownResponseBody` ?

**Comment by spence-s** [comment]
> How to retrieve a type with all available options to replace OptionsOfUnknownResponseBody ?

Oh I see 😄 . You should change it to `OptionsOfJSONResponseBody` now or optionally you `OptionsOfUnknownResponseBody | OptionsOfJSONResponseBody` should work I believe.

Let me know if that works for your use case now. I need to go back and update the types documentation I bit I believe.

**Comment by throrin19** [comment]
Thanks, it works fine. Sorry for this ticket :sweat_smile:
