### ISSUE TITLE
Unable to provide `resolveBodyOnly` option when specifying a generic type (v11)

### ISSUE THREAD

**Issue by pqvst** [sindresorhus/got#1167]
#### Describe the bug

- got version: 11.0.1
- Node.js version: v13.12.0
- OS & version: macOS (10.15.4)

After upgrading to v11 some of my existing v10 typescript code broke. Previously I was able to provide the `resolveBodyOnly` option when invoking `got` with a generic return type. After upgrading to v11 this overload does not compile.

#### Actual behavior
```
TSError: ⨯ Unable to compile TypeScript:
foo.ts:3:37 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Type 'true' is not assignable to type 'never'.

3 got<object>({ responseType: 'json', resolveBodyOnly: true });
                                      ~~~~~~~~~~~~~~~

  node_modules/got/dist/source/as-promise/types.d.ts:43:5
    43     resolveBodyOnly?: boolean;
           ~~~~~~~~~~~~~~~
    The expected type comes from property 'resolveBodyOnly' which is declared here on type 'Options & { isStream?: false; resolveBodyOnly?: false; responseType: "json"; } & ResponseBodyOnly'
  node_modules/got/dist/source/types.d.ts:57:5
    57     <T>(options: (OptionsOfJSONResponseBody & ResponseBodyOnly)): CancelableRequest<T>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

#### Expected behavior
I expect to be able to provide `resolveBodyOnly` when invoking got with a generic return type (this worked prior to v11). This should return a promise that resolves to the body (just `object` in this case).

#### Code to reproduce
```js
import got from 'got';
got<object>({ responseType: 'json' }); // ok
got<object>({ responseType: 'json', resolveBodyOnly: true }); // doesn't compile with v11
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.
