### ISSUE TITLE
Got v10 brainstorming

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#639]
I would prefer not doing a breaking release for a long time, but that doesn't mean we can't brainstorm.

Feel free to suggest breaking changes here. Suggestions should include use-cases and why it's worth doing a breaking change.

- [x] When the `query` string is an object, but not `URLSearchParams`, we should enforce that all the keys are `string|number`. To avoid issues like https://github.com/sindresorhus/got/issues/638.
- [x] Rename the `query` option to `searchParams`.
- [x] Use `undefined` instead of `null` whenever possible.

**Comment by sindresorhus** [comment]
@szmarczak What do you think about renaming the `query` option to `searchParams` to align with Ky and WHATWG URL terms. Would be more familiar for people coming from the browser.

**Comment by szmarczak** [comment]
100% yes!

**Comment by szmarczak** [comment]
options.retry.retries function should be called with the retry argument starting
from 1 instead of 0.

**Comment by UltCombo** [comment]
> options.retry.retries function should be called with the retry argument starting
> from 1 instead of 0.

Looks like that's the current (undocumented) behavior.

**Comment by szmarczak** [comment]
@UltCombo Yeah, you're right 😅 Sometimes I just think about one thing and do the second instead. Just a mistake. Edited :D

**Comment by javierblancosp** [comment]
What about when the request body is a nodejs stream (A multipart request), options.json can not be true. In the case i want to parse the response body as json i have to do it manually on a multipart request.I know is not a big deal but it could be nice to allow this somehow 🏋️

**Comment by szmarczak** [comment]
@javierblancosp why?

**Comment by javierblancosp** [comment]
@szmarczak mm i think if i expect a response to be a json the request body should not modify this, in may way of thinking :P

**Comment by szmarczak** [comment]
@javierblancosp Sorry for late response. Well, it's not a good idea. It has been discussed here: #174 #318 #383 #467 #511 #600 

Use this instead:

```js
const instance = got.extend({
    hooks: {
        beforeRequest: [
            options => {
                options.body = JSON.stringify(options.body);
            }
        ]
});

instance(url, options);
```

**Comment by sindresorhus** [comment]
@szmarczak Would it be hard to support both `query` and `searchParams` at the same time in v9? That would be optimal as we could then change the docs to `searchParams` so new users use the correct option naming and we could then slowly phase it out. Maybe just log a warning in v10 and then remove it in v11.

**Comment by szmarczak** [comment]
@sindresorhus Nah, only a few lines of code. I agree. I'll send a PR :)

**Comment by dylang** [comment]
Built-in typescript support? 

The third party one in `@types` was a great effort but lots of deficiencies, such as not supporting `extend` or getting response body as `string` when `json: true` is set.

**Comment by sindresorhus** [comment]
Yes, we would like to rewrite in TS. Just need the time or someone interested in doing the work.

**Comment by sindresorhus** [comment]
> replace uploadProgress and downloadProgress with hooks,

Why? I don't think this would benefit enough from hooks as you're actually not modifying anything in them.

> deprecate redirect event (use beforeRedirect hook instead),

Why? And are you sure `beforeRedirect` handles all the use-cases of the `redirect` event?

> make promise.on('error', cb) work?

Can you elaborate on how this is different from `promise.catch()` and what use-cases it solves?

**Comment by sindresorhus** [comment]
> Whenever you use promise or stream you want to use the same error handler (eg. you want to call specific logger). But you can still achieve that using handlers...

Isn't that exactly what the `beforeError` hook is for?

**Comment by szmarczak** [comment]
No. `beforeError` just modifies the error. But it still will be thrown; we don't want that. We want to catch the error using the same handler - whenever it's a promise or stream.

**Comment by sindresorhus** [comment]
@szmarczak Your mention use-case was logging though, which *could* be done in `beforeError`, but yes, actually handling the error cannot. I'm still dubious about the use-case. Have you actually encountered this need in real code?

**Comment by szmarczak** [comment]
> Have you actually encountered this need in real code?

Yup. Once. I was using it with `pino` logger and to not log 404 errors.

**Comment by sindresorhus** [comment]
@szmarczak Regarding https://github.com/sindresorhus/ky/pull/82/files#r248375929, I didn't realize Got had this behavior and I honestly don't like it. I think it's too magical. I think we should remove this behavior in v10. If you pass `body` when using GET, it should throw a helpful error instead. // @sholladay

**Comment by sindresorhus** [comment]
@szmarczak Thoughts on https://github.com/sindresorhus/got/issues/639#issuecomment-453808392 ?

**Comment by SleeplessByte** [comment]
Cross posting from ky#85

FWIW, at [`fuel`](https://github.com/kittinunf/fuel) we are running into servers now wanting `GET` requests with body.

Between RFC2616's obsoletion and RFCs 7230-7237 a few changes were made regarding this. Most importantly the following has been *removed*

> [RFC 216 Section 4.3](https://tools.ietf.org/html/rfc2616#section-4.3)
> [...] if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request.

To my understanding this means that servers and peers may now accept bodies for GET (and HEAD) requests. The behaviour, just like with `DELETE` requests are not defined.

> [RFC 7231 Section 4.3.1](https://tools.ietf.org/html/rfc7231#section-4.3.1) and [Section 4.3.2](https://tools.ietf.org/html/rfc7231#section-4.3.2)
> A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

**Comment by sindresorhus** [comment]
Another item we should do: Use `undefined` instead of `null` whenever possible.

**Comment by olistic** [comment]
Right now, if `options.body` is set and `options.method` is not, the latter will be set to `'POST'`, as documented [here](https://github.com/sindresorhus/got/tree/cd1235105423d110f1bb668e05dba16182be4fce#body). However, the same does not occur when `options.json` is set.

**Comment by szmarczak** [comment]
@olistic Could you please make another issue for that?

**Comment by olistic** [comment]
@szmarczak Reported in #736.

**Comment by szmarczak** [comment]
@sindresorhus Regarding the GET body thing: https://github.com/sindresorhus/got/pull/756 (it's ready to merge but IDK why I can't edit the post)

**Comment by szmarczak** [comment]
@sindresorhus Regarding the GET body thing: https://github.com/sindresorhus/got/pull/756 (it's ready to merge but IDK why I can't edit the post)

**Comment by szmarczak** [comment]
@sindresorhus Regarding the GET body thing: https://github.com/sindresorhus/got/pull/756 (it's ready to merge but IDK why I can't edit the post)

**Comment by szmarczak** [comment]
@sindresorhus Regarding the GET body thing: https://github.com/sindresorhus/got/pull/756 (it's ready to merge but IDK why I can't edit the post)

**Comment by ejmartin504** [comment]
@sindresorhus curious if there is a potential release date for v10? There are some features in v10 that would be super useful for my team in terms of migration path, in particular `resolveBodyOnly`. (Apologies if release calendar is publicly available elsewhere)

**Comment by sindresorhus** [comment]
@ejmartin504 No ETA, unfortunately, but we're hoping to get out a release soon. The main blocker is https://github.com/sindresorhus/got/issues/758 as we cannot do that in a minor release later on. You can see the remaining tasks here: https://github.com/sindresorhus/got/milestone/8

**Comment by timlesallen** [comment]
Hey.

Is `promise.json()` a v10 thing?  It's mentioned in the doco gut doesn't seem to work in 9.6.
```js
const got = require('got');
got('http://thing.com/blerg').json();
```
`TypeError: got(...).json is not a function`

Also, `resolveBodyOnly` is also documented but seems not be in 9.x?

**Comment by sindresorhus** [comment]
@timlesallen From the top of the readme:

> **This readme reflects the next major version that is currently in development. You probably want [the v9 readme](https://www.npmjs.com/package/got).**

**Comment by szmarczak** [comment]
Just a note to myself: https://github.com/sindresorhus/got/issues/602#issuecomment-455560208

**Comment by adityapatadia** [comment]
My favourite feature will be to allow changing https://github.com/lukechilds/cacheable-request module to something else. The development is too slow and bugs like caching of 304 response proves to be difficult to use it.

**Comment by sindresorhus** [comment]
Got v10 alpha.1 is now out: https://github.com/sindresorhus/got/issues/876
